CXX = g++            # 编译器
CXXFLAGS = -std=c++17 # 编译选项
SRC = m11215060.cpp        # 源文件
TARGET = m11215060    # 目标可执行文件

all: $(TARGET)

$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SRC)

clean:
	rm -f $(TARGET)
